// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdfvihnktdehybazzlte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZnZpaG5rdGRlaHliYXp6bHRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjQwNTEsImV4cCI6MjA2OTU0MDA1MX0.2cEESrr5x7M1u7LtsZh-rbTEx3WdCC--qo_A-WZhM7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});